package model;
// Generated 07-abr-2017 19:56:47 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {

     
     private String cuenta;
     private String contrasena;

    public Usuario() {
    }

	
    public Usuario(String cuenta) {
        this.cuenta = cuenta;
    }
    public Usuario(String cuenta, String contrasena) {
       this.cuenta = cuenta;
       this.contrasena = contrasena;
       
    }

   
    public String getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(String cuenta) {
        this.cuenta = cuenta;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }

    @Override
    public String toString() {
        return "Usuario{" + "cuenta=" + cuenta + ", contrasena=" + contrasena + '}';
    }




}


